"""
FastAPI router for the Autonomous Agent Runtime.
Exposes control and status so you can watch the agents make money.
"""

from __future__ import annotations

from fastapi import APIRouter, Depends
from sqlalchemy.orm import Session

from database import get_db
from .runtime import get_runtime

router = APIRouter(prefix="/api/agents", tags=["agents"])


@router.get("/status")
def agent_status(db: Session = Depends(get_db)):
    """Live status of the autonomous revenue runtime."""
    runtime = get_runtime(db_session_factory=lambda: db)
    return runtime.status()


@router.post("/start")
async def start_runtime(db: Session = Depends(get_db)):
    """Manually start (or restart) the autonomous revenue loop."""
    runtime = get_runtime(db_session_factory=lambda: db)
    await runtime.start()
    return {
        "status": "started",
        "message": "Autonomous agents are now running and generating revenue actions.",
        **runtime.status(),
    }


@router.post("/stop")
async def stop_runtime():
    """Stop the autonomous loop."""
    runtime = get_runtime()
    await runtime.stop()
    return {"status": "stopped", "message": "Runtime halted."}


@router.get("/events")
def recent_events(db: Session = Depends(get_db)):
    """Last revenue events generated by the agents."""
    runtime = get_runtime(db_session_factory=lambda: db)
    return {
        "events": runtime.engine.revenue_events[-50:],
        "total_logged": len(runtime.engine.revenue_events),
    }


@router.post("/force-cycle")
async def force_cycle(db: Session = Depends(get_db)):
    """Run one revenue cycle immediately (for testing / urgency)."""
    runtime = get_runtime(db_session_factory=lambda: db)
    if not runtime.running:
        await runtime.start()
    await runtime._execute_cycle()
    return {
        "status": "cycle_executed",
        "cycle": runtime.total_cycles,
        "events": runtime.engine.revenue_events[-5:],
    }
