"""
Garcar Enterprise Agent Registry
================================
Complete, typed catalog of the 341-agent lattice.
Every entry is immediately addressable by the orchestrator.
"""

from __future__ import annotations

from typing import Any, Dict, List, Optional

# Full lattice — source of truth for the Agent Network
AGENTS: List[Dict[str, Any]] = [
    {"id": 1, "name": "AccessibilityAudit", "type": "Specialist", "complexity": None, "vertical": "Design/Legal"},
    {"id": 2, "name": "AccreditationPrep", "type": None, "complexity": None, "vertical": "Education/Legal"},
    {"id": 3, "name": "AdRevenueOptimizer", "type": "Autonomous", "complexity": "Mega", "vertical": "Media/Marketing"},
    {"id": 4, "name": "AffiliateTracker", "type": None, "complexity": None, "vertical": "Marketing/Finance"},
    {"id": 5, "name": "AnalyticsInterpreter", "type": None, "complexity": None, "vertical": "Data Science"},
    {"id": 6, "name": "APIDesigner", "type": None, "complexity": None, "vertical": "Engineering"},
    {"id": 7, "name": "AppointmentOptimizer", "type": "Planner", "complexity": "Simple", "vertical": "Healthcare/Operations"},
    {"id": 8, "name": "AppSecBot", "type": "Specialist", "complexity": "Complex", "vertical": "Security"},
    {"id": 9, "name": "ArchitectBot", "type": "Planner", "complexity": None, "vertical": "Engineering"},
    {"id": 10, "name": "ArchiveManagerBot", "type": None, "complexity": None, "vertical": "Engineering/Media"},
    {"id": 11, "name": "AssetOrganizerBot", "type": "Reactive", "complexity": "Simple", "vertical": "Design/Media"},
    {"id": 12, "name": "AudienceAnalyzerMedia", "type": "Autonomous", "complexity": "Complex", "vertical": "Media"},
    {"id": 13, "name": "AuditTrailBot", "type": "Specialist", "complexity": "Moderate", "vertical": "Finance/Legal"},
    {"id": 14, "name": "AutoMLPilot", "type": "Autonomous", "complexity": "Mega", "vertical": "Data Science"},
    {"id": 15, "name": "BenefitsAdvisor", "type": "Conversational", "complexity": "Moderate", "vertical": "HR"},
    {"id": 16, "name": "BillingCoderAI", "type": "Specialist", "complexity": "Moderate", "vertical": "Healthcare"},
    {"id": 17, "name": "BOMManagerBot", "type": None, "complexity": None, "vertical": "Manufacturing"},
    {"id": 18, "name": "BrandKitManager", "type": "Reactive", "complexity": "Moderate", "vertical": "Design/Marketing"},
    {"id": 19, "name": "BrandSentiment", "type": "Evaluator", "complexity": "Moderate", "vertical": "Marketing"},
    {"id": 20, "name": "BrandVoiceEngine", "type": "Specialist", "complexity": None, "vertical": "Marketing"},
    {"id": 21, "name": "BudgetForecaster", "type": "Planner", "complexity": "Moderate", "vertical": "Finance"},
    {"id": 22, "name": "BugTriager", "type": None, "complexity": None, "vertical": "Engineering"},
    {"id": 23, "name": "BundleRecommender", "type": "Specialist", "complexity": "Simple", "vertical": "eCommerce"},
    {"id": 24, "name": "CampaignMind", "type": "Planner", "complexity": None, "vertical": "Marketing"},
    {"id": 25, "name": "CampusAnalytics", "type": None, "complexity": None, "vertical": "Education"},
    {"id": 26, "name": "CapacityForecasterEng", "type": None, "complexity": None, "vertical": "Engineering"},
    {"id": 27, "name": "CapacityPlanner", "type": "Planner", "complexity": None, "vertical": "Operations"},
    {"id": 28, "name": "CaseResearchAI", "type": "Autonomous", "complexity": "Complex", "vertical": "Legal/Research"},
    {"id": 29, "name": "CashFlowOracle", "type": "Planner", "complexity": None, "vertical": "Finance"},
    {"id": 30, "name": "CatalogEnricher", "type": None, "complexity": None, "vertical": "eCommerce/Data"},
    {"id": 31, "name": "ChainLink", "type": "Planner", "complexity": None, "vertical": "Supply Chain"},
    {"id": 32, "name": "ChannelMixOptimizer", "type": None, "complexity": None, "vertical": "Marketing"},
    {"id": 33, "name": "CheckoutOptimizer", "type": "Specialist", "complexity": "Moderate", "vertical": "eCommerce"},
    {"id": 34, "name": "CICDOptimizer", "type": None, "complexity": None, "vertical": "Engineering"},
    {"id": 35, "name": "CitationManagerAI", "type": "Specialist", "complexity": "Moderate", "vertical": "Research"},
    {"id": 36, "name": "CitationMapper", "type": "Specialist", "complexity": None, "vertical": "Research"},
    {"id": 37, "name": "ClassScheduler", "type": "Planner", "complexity": "Moderate", "vertical": "Education"},
    {"id": 38, "name": "ClauseExtractor", "type": "Specialist", "complexity": "Moderate", "vertical": "Legal"},
    {"id": 39, "name": "ClauseGuard", "type": "Specialist", "complexity": None, "vertical": "Legal"},
    {"id": 40, "name": "ClinicalTrialMatch", "type": "Autonomous", "complexity": "Complex", "vertical": "Healthcare"},
    {"id": 41, "name": "ClosingDocBot", "type": None, "complexity": None, "vertical": "Real Estate/Legal"},
    {"id": 42, "name": "CloudSecurityBot", "type": "Autonomous", "complexity": "Mega", "vertical": "Security"},
    {"id": 43, "name": "CMAGenerator", "type": None, "complexity": None, "vertical": "Real Estate"},
    {"id": 44, "name": "CodePilot", "type": "Autonomous", "complexity": None, "vertical": "Engineering"},
    {"id": 45, "name": "CodeRefactorAI", "type": None, "complexity": None, "vertical": "Engineering"},
    {"id": 46, "name": "CodeReviewBot", "type": None, "complexity": None, "vertical": "Engineering"},
    {"id": 47, "name": "ColdChainMonitor", "type": "Reactive", "complexity": "Moderate", "vertical": "Supply Chain"},
    {"id": 48, "name": "CollabFinderBot", "type": "Conversational", "complexity": "Moderate", "vertical": "Research"},
    {"id": 49, "name": "ColorPaletteGen", "type": "Specialist", "complexity": "Simple", "vertical": "Design"},
    {"id": 50, "name": "CommunityManager", "type": "Autonomous", "complexity": "Complex", "vertical": "Marketing/Community"},
    {"id": 51, "name": "CompAnalysisBot", "type": None, "complexity": None, "vertical": "Sales"},
    {"id": 52, "name": "ComparablesFinder", "type": None, "complexity": None, "vertical": "Real Estate"},
    {"id": 53, "name": "CompIntelBot", "type": None, "complexity": None, "vertical": "Sales"},
    {"id": 54, "name": "ComplianceChecker-Fin", "type": "Evaluator", "complexity": "Complex", "vertical": "Finance/Legal"},
    {"id": 55, "name": "ComplianceCyber", "type": "Planner", "complexity": "Complex", "vertical": "Security/Legal"},
    {"id": 56, "name": "ComplianceHIPAA", "type": "Evaluator", "complexity": "Complex", "vertical": "Healthcare/Legal"},
    {"id": 57, "name": "ComplianceOps", "type": "Evaluator", "complexity": "Complex", "vertical": "Legal/Compliance"},
    {"id": 58, "name": "ContainerTracker", "type": None, "complexity": None, "vertical": "Logistics"},
    {"id": 59, "name": "ContentAccessibility", "type": None, "complexity": None, "vertical": "Marketing/Content"},
    {"id": 60, "name": "ContentCalendarAI", "type": "Planner", "complexity": "Simple", "vertical": "Marketing"},
    {"id": 61, "name": "ContentRepurposer", "type": None, "complexity": None, "vertical": "Marketing/Media"},
    {"id": 62, "name": "ContentSchedulerMedia", "type": "Planner", "complexity": "Moderate", "vertical": "Media"},
    {"id": 63, "name": "ContractNego", "type": "Conversational", "complexity": "Complex", "vertical": "Legal"},
    {"id": 64, "name": "CopyEditorAI", "type": None, "complexity": None, "vertical": "Content"},
    {"id": 65, "name": "CopyrightGuardBot", "type": None, "complexity": None, "vertical": "Legal/Media"},
    {"id": 66, "name": "CostReducer", "type": None, "complexity": None, "vertical": "Finance/Operations"},
    {"id": 67, "name": "CreditRiskBot", "type": "Specialist", "complexity": "Complex", "vertical": "Finance"},
    {"id": 68, "name": "CryptoGuardBot", "type": "Specialist", "complexity": "Moderate", "vertical": "Finance/Security"},
    {"id": 69, "name": "CulturePulse", "type": "Evaluator", "complexity": None, "vertical": "HR"},
    {"id": 70, "name": "CurriculumForge", "type": None, "complexity": None, "vertical": "Education"},
    {"id": 71, "name": "CustomerJourney", "type": None, "complexity": None, "vertical": "Marketing/CX"},
    {"id": 72, "name": "DataCleanerBot", "type": "Specialist", "complexity": "Moderate", "vertical": "Data Engineering"},
    {"id": 73, "name": "DataDriftMonitor", "type": "Reactive", "complexity": "Moderate", "vertical": "Data Science"},
    {"id": 74, "name": "DataForge", "type": "Autonomous", "complexity": None, "vertical": "Data Engineering"},
    {"id": 75, "name": "DataGovernanceAI", "type": None, "complexity": None, "vertical": "Data/Legal"},
    {"id": 76, "name": "DataGovernor", "type": None, "complexity": None, "vertical": "Data/Legal"},
    {"id": 77, "name": "DataLossPreventor", "type": "Reactive", "complexity": "Complex", "vertical": "Security"},
    {"id": 78, "name": "DealCloser", "type": "Autonomous", "complexity": None, "vertical": "Sales"},
    {"id": 79, "name": "DealRoomOrch", "type": None, "complexity": None, "vertical": "Sales"},
    {"id": 80, "name": "DEIReportBot", "type": None, "complexity": None, "vertical": "HR"},
    {"id": 81, "name": "DemandForecasterSC", "type": "Autonomous", "complexity": "Complex", "vertical": "Supply Chain"},
    {"id": 82, "name": "DepSecurityScan", "type": None, "complexity": None, "vertical": "Security"},
    {"id": 83, "name": "DesignCritic", "type": None, "complexity": None, "vertical": "Design"},
    {"id": 84, "name": "DesignCritiqueAI", "type": None, "complexity": None, "vertical": "Design"},
    {"id": 85, "name": "DesignOpsManager", "type": "Orchestrator", "complexity": "Mega", "vertical": "Design"},
    {"id": 86, "name": "DesignSprintBot", "type": "Planner", "complexity": "Complex", "vertical": "Design"},
    {"id": 87, "name": "DesignSystemBot", "type": None, "complexity": None, "vertical": "Design"},
    {"id": 88, "name": "DesignTokenGen", "type": "Specialist", "complexity": "Moderate", "vertical": "Design"},
    {"id": 89, "name": "DevelopmentFeasibility", "type": None, "complexity": None, "vertical": "Real Estate/Product"},
    {"id": 90, "name": "DiagnosisAssist", "type": "Specialist", "complexity": None, "vertical": "Healthcare"},
    {"id": 91, "name": "DiversityTracker", "type": "Evaluator", "complexity": "Moderate", "vertical": "HR"},
    {"id": 92, "name": "DocGenBot", "type": None, "complexity": None, "vertical": "Engineering"},
    {"id": 93, "name": "DropshipManager", "type": "Orchestrator", "complexity": "Complex", "vertical": "eCommerce"},
    {"id": 94, "name": "DrugFormulary", "type": "Specialist", "complexity": "Simple", "vertical": "Healthcare"},
    {"id": 95, "name": "DynamicPricingAI", "type": "Autonomous", "complexity": "Mega", "vertical": "eCommerce"},
    {"id": 96, "name": "EDiscoveryBot", "type": None, "complexity": None, "vertical": "Legal"},
    {"id": 97, "name": "EditorialCalendarAI", "type": None, "complexity": None, "vertical": "Media/Marketing"},
    {"id": 98, "name": "EduTutor", "type": "Conversational", "complexity": None, "vertical": "Education"},
    {"id": 99, "name": "EHRMigrator", "type": None, "complexity": None, "vertical": "Healthcare"},
    {"id": 100, "name": "EmbeddingManager", "type": "Specialist", "complexity": "Moderate", "vertical": "Data Science"},
    {"id": 101, "name": "EndpointGuardBot", "type": None, "complexity": None, "vertical": "Security"},
    {"id": 102, "name": "EscalationBot", "type": "Reactive", "complexity": "Moderate", "vertical": "Support/Operations"},
    {"id": 103, "name": "EventPlannerAI", "type": "Planner", "complexity": "Moderate", "vertical": "Events"},
    {"id": 104, "name": "ExitInterviewBot", "type": "Conversational", "complexity": "Moderate", "vertical": "HR"},
    {"id": 105, "name": "ExpenseAuditor", "type": "Evaluator", "complexity": "Simple", "vertical": "Finance"},
    {"id": 106, "name": "ExperimentDesigner", "type": None, "complexity": None, "vertical": "Research"},
    {"id": 107, "name": "FacilityPlanner", "type": "Planner", "complexity": "Complex", "vertical": "Operations"},
    {"id": 108, "name": "FactCheckerAI", "type": None, "complexity": None, "vertical": "Research/Media"},
    {"id": 109, "name": "FeatureAdoptionBot", "type": None, "complexity": None, "vertical": "Product"},
    {"id": 110, "name": "FeatureEngineerAI", "type": None, "complexity": None, "vertical": "Data Science"},
    {"id": 111, "name": "FeatureFlagBot", "type": None, "complexity": None, "vertical": "Engineering/Product"},
    {"id": 112, "name": "FeatureSpecWriter", "type": None, "complexity": None, "vertical": "Product"},
    {"id": 113, "name": "FeedbackLoopAI", "type": "Orchestrator", "complexity": "Complex", "vertical": "Product"},
    {"id": 114, "name": "FieldTripPlanner", "type": "Planner", "complexity": "Simple", "vertical": "Education"},
    {"id": 115, "name": "FinPlannerAI", "type": None, "complexity": None, "vertical": "Finance"},
    {"id": 116, "name": "FinReportGen", "type": "Specialist", "complexity": "Moderate", "vertical": "Finance"},
    {"id": 117, "name": "ForecastPro", "type": "Specialist", "complexity": "Complex", "vertical": "Sales"},
    {"id": 118, "name": "ForensicsBot", "type": None, "complexity": None, "vertical": "Security/Legal"},
    {"id": 119, "name": "FraudDetectorEC", "type": "Autonomous", "complexity": "Mega", "vertical": "eCommerce/Security"},
    {"id": 120, "name": "FraudScreener", "type": "Reactive", "complexity": "Complex", "vertical": "Finance/Security"},
    {"id": 121, "name": "FraudSentinel", "type": "Reactive", "complexity": None, "vertical": "Security/Finance"},
    {"id": 122, "name": "FreightAuditBot", "type": "Evaluator", "complexity": "Moderate", "vertical": "Logistics"},
    {"id": 123, "name": "FundingTrackerAI", "type": "Planner", "complexity": "Moderate", "vertical": "Finance/Research"},
    {"id": 124, "name": "GradeAssist", "type": None, "complexity": None, "vertical": "Education"},
    {"id": 125, "name": "GrantWriter", "type": "Autonomous", "complexity": None, "vertical": "Research/Nonprofit"},
    {"id": 126, "name": "GrantWriterBot", "type": "Specialist", "complexity": "Complex", "vertical": "Research/Nonprofit"},
    {"id": 127, "name": "GraphAnalyticsAI", "type": None, "complexity": None, "vertical": "Data Science"},
    {"id": 128, "name": "GraphAnalyzer", "type": None, "complexity": None, "vertical": "Data Science"},
    {"id": 129, "name": "HealthRecordSync", "type": "Reactive", "complexity": "Moderate", "vertical": "Healthcare"},
    {"id": 130, "name": "HealthScoreBot", "type": "Specialist", "complexity": None, "vertical": "Healthcare"},
    {"id": 131, "name": "HomeworkHelper", "type": "Conversational", "complexity": "Moderate", "vertical": "Education"},
    {"id": 132, "name": "HypothesisGenBot", "type": None, "complexity": None, "vertical": "Research"},
    {"id": 133, "name": "IAMManagerBot", "type": None, "complexity": None, "vertical": "Security"},
    {"id": 134, "name": "IconForgeAI", "type": None, "complexity": None, "vertical": "Design"},
    {"id": 135, "name": "IllustrationBot", "type": None, "complexity": None, "vertical": "Design"},
    {"id": 136, "name": "IncidentResponder", "type": "Reactive", "complexity": "Complex", "vertical": "Security"},
    {"id": 137, "name": "IncidentResponseCyber", "type": "Orchestrator", "complexity": "Mega", "vertical": "Security"},
    {"id": 138, "name": "InfluencerMatch", "type": "Specialist", "complexity": "Moderate", "vertical": "Marketing"},
    {"id": 139, "name": "InfraScaler", "type": "Autonomous", "complexity": "Complex", "vertical": "Engineering/Cloud"},
    {"id": 140, "name": "InspectionReportBot", "type": "Specialist", "complexity": "Moderate", "vertical": "Real Estate"},
    {"id": 141, "name": "InsuranceCalc", "type": "Specialist", "complexity": "Moderate", "vertical": "Finance/Insurance"},
    {"id": 142, "name": "IntegrationHelper", "type": "Conversational", "complexity": "Moderate", "vertical": "Engineering"},
    {"id": 143, "name": "InventoryForecaster", "type": None, "complexity": None, "vertical": "Supply Chain"},
    {"id": 144, "name": "InventoryPlannerSC", "type": "Planner", "complexity": "Complex", "vertical": "Supply Chain"},
    {"id": 145, "name": "InventorySyncBot", "type": "Reactive", "complexity": "Complex", "vertical": "eCommerce"},
    {"id": 146, "name": "InvestmentAnalyzerRE", "type": None, "complexity": None, "vertical": "Real Estate/Finance"},
    {"id": 147, "name": "InvestmentModeler", "type": None, "complexity": None, "vertical": "Real Estate/Finance"},
    {"id": 148, "name": "IPWatchBot", "type": None, "complexity": None, "vertical": "Legal"},
    {"id": 149, "name": "IRBComplianceBot", "type": None, "complexity": None, "vertical": "Healthcare/Legal"},
    {"id": 150, "name": "JTBDAnalyzer", "type": None, "complexity": None, "vertical": "Product/UX"},
    {"id": 151, "name": "LabResultInterp", "type": None, "complexity": None, "vertical": "Healthcare"},
    {"id": 152, "name": "LanguageTutorAI", "type": "Conversational", "complexity": "Complex", "vertical": "Education"},
    {"id": 153, "name": "LayoutGenerator", "type": None, "complexity": None, "vertical": "Design"},
    {"id": 154, "name": "LDPathfinder", "type": None, "complexity": None, "vertical": "Education"},
    {"id": 155, "name": "LeadNurtureBot", "type": None, "complexity": None, "vertical": "Marketing/Sales"},
    {"id": 156, "name": "LeadQualifierRE", "type": "Autonomous", "complexity": "Moderate", "vertical": "Real Estate"},
    {"id": 157, "name": "LearningPathAI", "type": None, "complexity": None, "vertical": "Education"},
    {"id": 158, "name": "LeaseAnalyzer", "type": "Specialist", "complexity": "Complex", "vertical": "Real Estate/Legal"},
    {"id": 159, "name": "LedgerBot", "type": "Specialist", "complexity": None, "vertical": "Finance"},
    {"id": 160, "name": "LegalBillAuditor", "type": "Evaluator", "complexity": "Simple", "vertical": "Legal/Finance"},
    {"id": 161, "name": "LessonPlanAI", "type": None, "complexity": None, "vertical": "Education"},
    {"id": 162, "name": "LibraryRecommend", "type": "Specialist", "complexity": "Simple", "vertical": "Education"},
    {"id": 163, "name": "ListingOptimizer", "type": None, "complexity": None, "vertical": "Real Estate/eCommerce"},
    {"id": 164, "name": "LogisticsOptimizer", "type": "Planner", "complexity": "Mega", "vertical": "Logistics"},
    {"id": 165, "name": "LoyaltyProgramAI", "type": None, "complexity": None, "vertical": "eCommerce/Marketing"},
    {"id": 166, "name": "MaintenanceTrackerRE", "type": None, "complexity": None, "vertical": "Real Estate"},
    {"id": 167, "name": "ManuscriptPrepBot", "type": None, "complexity": None, "vertical": "Research/Publishing"},
    {"id": 168, "name": "MarketAnalyzerRE", "type": None, "complexity": None, "vertical": "Real Estate"},
    {"id": 169, "name": "MarketplaceBot", "type": None, "complexity": None, "vertical": "eCommerce"},
    {"id": 170, "name": "MarketResearchBot", "type": None, "complexity": None, "vertical": "Research/Marketing"},
    {"id": 171, "name": "MarketSizer", "type": None, "complexity": None, "vertical": "Research/Market"},
    {"id": 172, "name": "MarketTrendBot", "type": None, "complexity": None, "vertical": "Market Research"},
    {"id": 173, "name": "MedAssist", "type": "Conversational", "complexity": None, "vertical": "Healthcare"},
    {"id": 174, "name": "MediaAnalyticsAI", "type": "Specialist", "complexity": "Complex", "vertical": "Media"},
    {"id": 175, "name": "MediaBuyerBot", "type": "Autonomous", "complexity": "Complex", "vertical": "Media/Marketing"},
    {"id": 176, "name": "MediaMix", "type": "Autonomous", "complexity": None, "vertical": "Media"},
    {"id": 177, "name": "MentalHealthScreen", "type": "Conversational", "complexity": "Complex", "vertical": "Healthcare"},
    {"id": 178, "name": "MigrationAssist", "type": "Orchestrator", "complexity": "Mega", "vertical": "Engineering"},
    {"id": 179, "name": "MigrationPlanner", "type": "Planner", "complexity": "Mega", "vertical": "Engineering"},
    {"id": 180, "name": "MLOpsManager", "type": "Orchestrator", "complexity": "Mega", "vertical": "Data Science"},
    {"id": 181, "name": "ModelExplainer", "type": None, "complexity": None, "vertical": "Data Science"},
    {"id": 182, "name": "ModelSelector", "type": None, "complexity": None, "vertical": "Data Science"},
    {"id": 183, "name": "MoodBoardGen", "type": "Specialist", "complexity": "Simple", "vertical": "Design"},
    {"id": 184, "name": "MortgageCalcBot", "type": "Conversational", "complexity": "Simple", "vertical": "Real Estate/Finance"},
    {"id": 185, "name": "NetworkDesignerSC", "type": "Planner", "complexity": "Mega", "vertical": "Supply Chain"},
    {"id": 186, "name": "NetworkMonitorAI", "type": "Reactive", "complexity": "Complex", "vertical": "Security/Engineering"},
    {"id": 187, "name": "NewsletterForge", "type": "Specialist", "complexity": "Moderate", "vertical": "Marketing"},
    {"id": 188, "name": "NLPPipelineBot", "type": "Specialist", "complexity": "Complex", "vertical": "Data Science"},
    {"id": 189, "name": "NLPToolkitBot", "type": "Specialist", "complexity": "Moderate", "vertical": "Data Science"},
    {"id": 190, "name": "NPSAnalyzer", "type": None, "complexity": None, "vertical": "Customer Success"},
    {"id": 191, "name": "ObjHandlerX", "type": None, "complexity": None, "vertical": "Sales"},
    {"id": 192, "name": "OfferLetterGen", "type": None, "complexity": None, "vertical": "HR"},
    {"id": 193, "name": "OnboardGuide", "type": None, "complexity": None, "vertical": "HR"},
    {"id": 194, "name": "OnboardPro", "type": "Orchestrator", "complexity": None, "vertical": "HR"},
    {"id": 195, "name": "OpenHousePlanner", "type": "Planner", "complexity": "Simple", "vertical": "Real Estate"},
    {"id": 196, "name": "OpenScienceBot", "type": None, "complexity": None, "vertical": "Research"},
    {"id": 197, "name": "OpsEngine", "type": "Orchestrator", "complexity": None, "vertical": "Operations"},
    {"id": 198, "name": "PackagingOptimizer", "type": None, "complexity": None, "vertical": "Design/Manufacturing"},
    {"id": 199, "name": "ParentCommBot", "type": None, "complexity": None, "vertical": "Education"},
    {"id": 200, "name": "PartnerMatch", "type": None, "complexity": None, "vertical": "Sales/Partnerships"},
    {"id": 201, "name": "PatchManagerBot", "type": None, "complexity": None, "vertical": "Engineering/Security"},
    {"id": 202, "name": "PatentDrafter", "type": "Specialist", "complexity": "Complex", "vertical": "Legal"},
    {"id": 203, "name": "PatentSearchAI", "type": "Specialist", "complexity": "Complex", "vertical": "Legal"},
    {"id": 204, "name": "PatientComms", "type": "Conversational", "complexity": "Moderate", "vertical": "Healthcare"},
    {"id": 205, "name": "PatientRiskScore", "type": "Evaluator", "complexity": "Complex", "vertical": "Healthcare"},
    {"id": 206, "name": "PayEquityBot", "type": "Evaluator", "complexity": "Complex", "vertical": "HR"},
    {"id": 207, "name": "PayrollGuard", "type": "Reactive", "complexity": "Moderate", "vertical": "HR/Finance"},
    {"id": 208, "name": "PaywallOptimizer", "type": None, "complexity": None, "vertical": "Media/Finance"},
    {"id": 209, "name": "PeerReviewAssist", "type": "Evaluator", "complexity": "Complex", "vertical": "Research/Education"},
    {"id": 210, "name": "PeerReviewBot", "type": "Evaluator", "complexity": "Moderate", "vertical": "Education"},
    {"id": 211, "name": "PenTestAssist", "type": None, "complexity": None, "vertical": "Security"},
    {"id": 212, "name": "PerformReviewAI", "type": None, "complexity": None, "vertical": "HR"},
    {"id": 213, "name": "PersonaBuilder", "type": None, "complexity": None, "vertical": "Marketing/UX"},
    {"id": 214, "name": "PersonalizationBot", "type": "Specialist", "complexity": "Complex", "vertical": "Marketing/eCommerce"},
    {"id": 215, "name": "PersonaRefiner", "type": None, "complexity": None, "vertical": "Marketing"},
    {"id": 216, "name": "PhishGuard", "type": "Reactive", "complexity": None, "vertical": "Security"},
    {"id": 217, "name": "PhishingDetector", "type": "Reactive", "complexity": "Moderate", "vertical": "Security"},
    {"id": 218, "name": "PipelineCleaner", "type": None, "complexity": None, "vertical": "Sales/Data"},
    {"id": 219, "name": "PipelineOrchDS", "type": "Orchestrator", "complexity": "Mega", "vertical": "Data Science"},
    {"id": 220, "name": "PipelineProspector", "type": "Reactive", "complexity": None, "vertical": "Sales"},
    {"id": 221, "name": "PlagiarismGuard", "type": None, "complexity": None, "vertical": "Content/Legal"},
    {"id": 222, "name": "PodcastEditorAI", "type": None, "complexity": None, "vertical": "Media"},
    {"id": 223, "name": "PolicyDrafter", "type": None, "complexity": None, "vertical": "HR/Legal"},
    {"id": 224, "name": "PolicyQABot", "type": "Conversational", "complexity": "Simple", "vertical": "HR/Legal"},
    {"id": 225, "name": "PopHealthAnalyzer", "type": "Planner", "complexity": "Complex", "vertical": "Healthcare"},
    {"id": 226, "name": "PortfolioAnalyzer", "type": None, "complexity": None, "vertical": "Finance/Design"},
    {"id": 227, "name": "PRDraftBot", "type": "Specialist", "complexity": "Moderate", "vertical": "Marketing/PR"},
    {"id": 228, "name": "PricingAdvisor", "type": "Planner", "complexity": "Complex", "vertical": "Sales/Finance"},
    {"id": 229, "name": "PricingDynamo", "type": "Autonomous", "complexity": None, "vertical": "Sales/Finance"},
    {"id": 230, "name": "PricingModeler", "type": "Specialist", "complexity": "Complex", "vertical": "Sales/Finance"},
    {"id": 231, "name": "PrivacyGuardAI", "type": None, "complexity": None, "vertical": "Legal/Security"},
    {"id": 232, "name": "ProactiveAlertBot", "type": "Reactive", "complexity": "Complex", "vertical": "Operations"},
    {"id": 233, "name": "ProcessMiner", "type": None, "complexity": None, "vertical": "Operations"},
    {"id": 234, "name": "ProcurementBot", "type": "Orchestrator", "complexity": "Complex", "vertical": "Procurement"},
    {"id": 235, "name": "ProductDescWriter", "type": None, "complexity": None, "vertical": "eCommerce/Marketing"},
    {"id": 236, "name": "ProductMetricsAI", "type": None, "complexity": None, "vertical": "Product"},
    {"id": 237, "name": "ProductOpsBot", "type": "Orchestrator", "complexity": "Mega", "vertical": "Product"},
    {"id": 238, "name": "ProductRecEngine", "type": None, "complexity": None, "vertical": "eCommerce"},
    {"id": 239, "name": "PropertyManagerAI", "type": "Orchestrator", "complexity": "Mega", "vertical": "Real Estate"},
    {"id": 240, "name": "PropertyMarketingAI", "type": None, "complexity": None, "vertical": "Real Estate"},
    {"id": 241, "name": "PropertyPulse", "type": None, "complexity": None, "vertical": "Real Estate"},
    {"id": 242, "name": "PropertyTaxBot", "type": "Specialist", "complexity": "Moderate", "vertical": "Real Estate/Finance"},
    {"id": 243, "name": "PropertyValuator", "type": "Specialist", "complexity": "Complex", "vertical": "Real Estate"},
    {"id": 244, "name": "ProposalPro", "type": None, "complexity": None, "vertical": "Sales"},
    {"id": 245, "name": "PrototypeFeedback", "type": None, "complexity": None, "vertical": "Design/UX"},
    {"id": 246, "name": "PRSummarizer", "type": None, "complexity": None, "vertical": "Marketing/PR"},
    {"id": 247, "name": "QualityInspector", "type": None, "complexity": None, "vertical": "Manufacturing/Operations"},
    {"id": 248, "name": "QuizForge", "type": None, "complexity": None, "vertical": "Education"},
    {"id": 249, "name": "QuoteCraft", "type": "Specialist", "complexity": None, "vertical": "Sales"},
    {"id": 250, "name": "RecommenderEngine", "type": None, "complexity": None, "vertical": "eCommerce/Media"},
    {"id": 251, "name": "RECRMBot", "type": "Orchestrator", "complexity": "Complex", "vertical": "Real Estate"},
    {"id": 252, "name": "ReferenceChecker", "type": "Reactive", "complexity": "Simple", "vertical": "HR"},
    {"id": 253, "name": "RehabScheduler", "type": None, "complexity": None, "vertical": "Healthcare"},
    {"id": 254, "name": "RentOptimizer", "type": None, "complexity": None, "vertical": "Real Estate"},
    {"id": 255, "name": "REPortfolioBot", "type": None, "complexity": None, "vertical": "Real Estate"},
    {"id": 256, "name": "ReproducibilityBot", "type": "Evaluator", "complexity": "Complex", "vertical": "Research/Data"},
    {"id": 257, "name": "ResearchVizBot", "type": "Specialist", "complexity": "Moderate", "vertical": "Research"},
    {"id": 258, "name": "ResourceAllocator", "type": "Planner", "complexity": "Moderate", "vertical": "Operations"},
    {"id": 259, "name": "RetentionEngine", "type": "Reactive", "complexity": None, "vertical": "Customer Success"},
    {"id": 260, "name": "ReturnLogisticsBot", "type": "Planner", "complexity": "Moderate", "vertical": "eCommerce/Logistics"},
    {"id": 261, "name": "ReturnOptimizer", "type": "Planner", "complexity": "Moderate", "vertical": "eCommerce"},
    {"id": 262, "name": "RevenuePredictor", "type": "Specialist", "complexity": "Complex", "vertical": "Finance"},
    {"id": 263, "name": "ReviewAnalyst", "type": "Reactive", "complexity": None, "vertical": "Customer Success"},
    {"id": 264, "name": "ReviewAnalyzer", "type": None, "complexity": None, "vertical": "eCommerce/Product"},
    {"id": 265, "name": "RevOpsBot", "type": None, "complexity": None, "vertical": "Sales/Operations"},
    {"id": 266, "name": "RightsManagerBot", "type": None, "complexity": None, "vertical": "Media/Legal"},
    {"id": 267, "name": "RiskAssessAI", "type": "Evaluator", "complexity": "Complex", "vertical": "Finance/Risk"},
    {"id": 268, "name": "RoadmapPrioritizer", "type": "Planner", "complexity": None, "vertical": "Product"},
    {"id": 269, "name": "RxInteractionCheck", "type": None, "complexity": None, "vertical": "Healthcare"},
    {"id": 270, "name": "S&OPPlannerAI", "type": None, "complexity": None, "vertical": "Supply Chain"},
    {"id": 271, "name": "SCAnalyticsBot", "type": None, "complexity": None, "vertical": "Supply Chain"},
    {"id": 272, "name": "SchemaEvolver", "type": "Specialist", "complexity": "Moderate", "vertical": "Data/Engineering"},
    {"id": 273, "name": "ScholarshipMatch", "type": "Specialist", "complexity": "Moderate", "vertical": "Education"},
    {"id": 274, "name": "SecurityAwarenessBot", "type": None, "complexity": None, "vertical": "Security"},
    {"id": 275, "name": "SecurityReportGen", "type": "Specialist", "complexity": "Moderate", "vertical": "Security"},
    {"id": 276, "name": "SentinelAI", "type": None, "complexity": None, "vertical": "Security"},
    {"id": 277, "name": "SEOStrategyBot", "type": None, "complexity": None, "vertical": "Marketing"},
    {"id": 278, "name": "ShiftScheduler", "type": None, "complexity": None, "vertical": "HR/Operations"},
    {"id": 279, "name": "ShippingOptimizer", "type": "Planner", "complexity": "Moderate", "vertical": "eCommerce/Logistics"},
    {"id": 280, "name": "ShopStream", "type": "Orchestrator", "complexity": None, "vertical": "eCommerce"},
    {"id": 281, "name": "SkillAssessor", "type": None, "complexity": None, "vertical": "Education/HR"},
    {"id": 282, "name": "SLAMonitor", "type": "Reactive", "complexity": "Moderate", "vertical": "Operations"},
    {"id": 283, "name": "SOCAnalyzerAI", "type": "Autonomous", "complexity": "Mega", "vertical": "Security"},
    {"id": 284, "name": "SocialListenBot", "type": "Reactive", "complexity": "Moderate", "vertical": "Marketing"},
    {"id": 285, "name": "SOPGenerator", "type": None, "complexity": None, "vertical": "Operations"},
    {"id": 286, "name": "SpecialEdAssist", "type": "Specialist", "complexity": "Complex", "vertical": "Education"},
    {"id": 287, "name": "StreamProcessor", "type": None, "complexity": None, "vertical": "Data Engineering"},
    {"id": 288, "name": "StreamProcessorBot", "type": None, "complexity": None, "vertical": "Data Engineering"},
    {"id": 289, "name": "StudentRiskAlert", "type": "Reactive", "complexity": "Moderate", "vertical": "Education"},
    {"id": 290, "name": "SubtitleGenAI", "type": None, "complexity": None, "vertical": "Media"},
    {"id": 291, "name": "SuccessionPlanner", "type": None, "complexity": None, "vertical": "HR"},
    {"id": 292, "name": "SuccessRadar", "type": "Reactive", "complexity": None, "vertical": "Customer Success"},
    {"id": 293, "name": "SupplierDiversityBot", "type": "Specialist", "complexity": "Moderate", "vertical": "Procurement/HR"},
    {"id": 294, "name": "SupplierEvalBot", "type": None, "complexity": None, "vertical": "Procurement"},
    {"id": 295, "name": "SupplierScorer", "type": None, "complexity": None, "vertical": "Procurement"},
    {"id": 296, "name": "SupplyRiskMonitor", "type": "Reactive", "complexity": "Complex", "vertical": "Supply Chain"},
    {"id": 297, "name": "SurgicalPlanAI", "type": None, "complexity": None, "vertical": "Healthcare"},
    {"id": 298, "name": "SurveyDesignerAI", "type": None, "complexity": None, "vertical": "Research/UX"},
    {"id": 299, "name": "SustainabilitySC", "type": None, "complexity": None, "vertical": "Supply Chain"},
    {"id": 300, "name": "SyndicationBot", "type": "Orchestrator", "complexity": "Complex", "vertical": "Marketing/Media"},
    {"id": 301, "name": "SyntheticDataGen", "type": None, "complexity": None, "vertical": "Data Science"},
    {"id": 302, "name": "TalentScout", "type": "Planner", "complexity": None, "vertical": "HR"},
    {"id": 303, "name": "TalentSourcer", "type": "Autonomous", "complexity": "Complex", "vertical": "HR"},
    {"id": 304, "name": "TechDebtTracker", "type": "Evaluator", "complexity": "Moderate", "vertical": "Engineering"},
    {"id": 305, "name": "TechSpecReviewer", "type": None, "complexity": None, "vertical": "Engineering"},
    {"id": 306, "name": "TenantScreener", "type": None, "complexity": None, "vertical": "Real Estate"},
    {"id": 307, "name": "TerritoryMapper", "type": None, "complexity": None, "vertical": "Sales"},
    {"id": 308, "name": "TestForge", "type": "Autonomous", "complexity": None, "vertical": "Engineering"},
    {"id": 309, "name": "ThreatDetectorAI", "type": "Reactive", "complexity": "Mega", "vertical": "Security"},
    {"id": 310, "name": "ThreatIntelBot", "type": "Specialist", "complexity": "Complex", "vertical": "Security"},
    {"id": 311, "name": "ThumbnailOptimizer", "type": "Specialist", "complexity": "Simple", "vertical": "Media"},
    {"id": 312, "name": "TicketRouter", "type": None, "complexity": None, "vertical": "Support"},
    {"id": 313, "name": "TitleSearchBot", "type": None, "complexity": None, "vertical": "Real Estate/Legal"},
    {"id": 314, "name": "TradeComplianceBot", "type": None, "complexity": None, "vertical": "Legal/Trade"},
    {"id": 315, "name": "TrademarkBot", "type": "Specialist", "complexity": "Moderate", "vertical": "Legal"},
    {"id": 316, "name": "TranscriptionBot", "type": "Specialist", "complexity": "Moderate", "vertical": "Media"},
    {"id": 317, "name": "TreasuryManager", "type": "Orchestrator", "complexity": "Mega", "vertical": "Finance"},
    {"id": 318, "name": "TrendRadar", "type": None, "complexity": None, "vertical": "Marketing/Media"},
    {"id": 319, "name": "TrendSpotterMedia", "type": "Reactive", "complexity": "Moderate", "vertical": "Media"},
    {"id": 320, "name": "TriageBot", "type": None, "complexity": None, "vertical": "Healthcare"},
    {"id": 321, "name": "TutorMatchBot", "type": "Specialist", "complexity": "Simple", "vertical": "Education"},
    {"id": 322, "name": "TypeScaleBot", "type": None, "complexity": None, "vertical": "Design"},
    {"id": 323, "name": "UserInsightMiner", "type": None, "complexity": None, "vertical": "Product/UX"},
    {"id": 324, "name": "UXResearchBot", "type": "Evaluator", "complexity": None, "vertical": "Design/UX"},
    {"id": 325, "name": "VaccineTracker", "type": None, "complexity": None, "vertical": "Healthcare"},
    {"id": 326, "name": "ValuationBot", "type": None, "complexity": None, "vertical": "Real Estate/Finance"},
    {"id": 327, "name": "VendorManager", "type": None, "complexity": None, "vertical": "Procurement"},
    {"id": 328, "name": "VideoClipperBot", "type": "Specialist", "complexity": "Moderate", "vertical": "Media"},
    {"id": 329, "name": "ViralHookGen", "type": None, "complexity": None, "vertical": "Marketing/Content"},
    {"id": 330, "name": "VirtualTourBot", "type": None, "complexity": None, "vertical": "Real Estate"},
    {"id": 331, "name": "VirtualTourGen", "type": "Specialist", "complexity": "Complex", "vertical": "Real Estate"},
    {"id": 332, "name": "VulnHunter", "type": None, "complexity": None, "vertical": "Security"},
    {"id": 333, "name": "VulnScannerBot", "type": "Autonomous", "complexity": "Complex", "vertical": "Security"},
    {"id": 334, "name": "WarehouseBot", "type": "Autonomous", "complexity": "Complex", "vertical": "Supply Chain/Warehouse"},
    {"id": 335, "name": "WasteReducer", "type": None, "complexity": None, "vertical": "Operations/Sustainability"},
    {"id": 336, "name": "WebinarEngine", "type": None, "complexity": None, "vertical": "Marketing/Media"},
    {"id": 337, "name": "WhistleblowBot", "type": None, "complexity": None, "vertical": "HR/Legal"},
    {"id": 338, "name": "WireframeDescriber", "type": "Specialist", "complexity": "Moderate", "vertical": "Design"},
    {"id": 339, "name": "WorkflowMapper", "type": None, "complexity": None, "vertical": "Operations"},
    {"id": 340, "name": "ZeroTrustBot", "type": None, "complexity": None, "vertical": "Security"},
    {"id": 341, "name": "ZoningAnalyzer", "type": None, "complexity": None, "vertical": "Real Estate/Legal"},
]


def get_agent(name: str) -> Optional[Dict[str, Any]]:
    """Retrieve a single agent by exact name."""
    for agent in AGENTS:
        if agent["name"].lower() == name.lower():
            return agent
    return None


def list_by_vertical(vertical: str) -> List[Dict[str, Any]]:
    """Return all agents whose vertical contains the given string."""
    vertical = vertical.lower()
    return [a for a in AGENTS if a["vertical"] and vertical in a["vertical"].lower()]


def list_by_type(agent_type: str) -> List[Dict[str, Any]]:
    """Return all agents of a given type (Specialist, Autonomous, etc.)."""
    agent_type = agent_type.lower()
    return [a for a in AGENTS if a["type"] and a["type"].lower() == agent_type]


def list_by_complexity(complexity: str) -> List[Dict[str, Any]]:
    """Return all agents of a given complexity tier."""
    complexity = complexity.lower()
    return [a for a in AGENTS if a["complexity"] and a["complexity"].lower() == complexity]
